import Footer from '@/components/Footer';
import './Graduacion2027.css';

const media = '/media/graduacion-2027/';
const contact = 'https://wa.me/523111034737?text=' + encodeURIComponent('Hola, me gustaría recibir información del viaje de graduación 2027 del Colegio de Ciencias y Letras de Tepic, organizado por Instituto Ascendant.');
const gallery = [
  ['room_queen.jpg', 'Habitación Ocean Front con dos camas queen'],
  ['room_king.jpg', 'Habitación Ocean Front con cama king'],
  ['pool.jpg', 'Albercas y playa'],
  ['restaurant.jpg', 'Restaurante Vela'],
  ['fitness.jpg', 'Gimnasio'],
  ['kids.jpg', 'Club infantil'],
];
const included = [
  ['01', 'Hospedaje todo incluido', '4 días y 3 noches en Hilton Vallarta Riviera. All inclusive durante la estancia, en habitación Ocean Front.'],
  ['02', 'Aventura en Barco Pirata', 'Tour diurno con show, actividades y alimentos a bordo para disfrutar en familia.'],
  ['03', 'Traslados para el tour', 'Transporte hotel–embarcadero y embarcadero–hotel incluido.'],
  ['04', 'Fotografías al atardecer', 'Recuerdos de esta etapa, con el Pacífico y la luz del atardecer como escenario.'],
  ['05', 'Cena de gala de graduación', 'Una noche especial para celebrar con compañeros y familia.'],
];
const rates = [
  ['Graduado', '$16,490'], ['Menor hasta 4 años', 'Sin costo'], ['Menor de 5 a 12 años, habitación compartida', '$7,990'],
  ['Adulto de 13 años o más, habitación compartida', '$17,790'], ['Tercer adulto de 13 años o más, habitación compartida', '$14,290'], ['Adulto de 13 años o más, habitación individual', '$22,490'],
];
export default function Graduacion2027({ appearance = "light" }: { appearance?: "light" | "dark" }) {
  return <div className={"graduacion-page" + (appearance === "light" ? " grad-light" : "")}>
    <a className="grad-skip" href="#contenido">Ir al contenido</a>
    <header className="grad-nav"><a href="/" aria-label="Instituto Ascendant, inicio"><img src={media + 'logo.png'} alt="Instituto Ascendant" width="150" height="76" /></a><nav aria-label="Navegación del viaje"><a href="#hotel">El hotel</a><a href="#paquete">El paquete</a><a href="#reservacion" className="grad-button small">Solicitar información ↗</a></nav></header>
    <main id="contenido">
      <section className="grad-hero" aria-labelledby="grad-title">
        <img className="grad-hero-image" src={media + 'hero.jpg'} alt="Hilton Vallarta Riviera frente al Pacífico" width="1920" height="1080" fetchPriority="high" />
        <div className="grad-hero-content"><p className="grad-eyebrow">Colegio de Ciencias y Letras de Tepic · Secundaria</p><h1 id="grad-title">Una etapa termina.<br /><em>La aventura comienza.</em></h1><p className="grad-hero-description">Viaje de graduación 2027 · Puerto Vallarta<br />Un encuentro de amigos, familia y recuerdos frente al mar.</p><div className="grad-facts"><span><strong>27–30</strong> mayo de 2027</span><span><strong>4 días</strong> / 3 noches</span><span><strong>Hilton</strong> Vallarta Riviera</span></div><div className="grad-actions"><a href="#video" className="grad-button">Descubre el viaje ↓</a><a href="#reservacion" className="grad-link">Ver paquete y tarifas ↗</a></div><p className="grad-organizer">Organiza: <strong>Instituto Ascendant</strong></p></div>
        <span className="grad-hero-caption">Fotografía de referencia del hotel Hilton</span>
      </section>
      <section id="video" className="grad-section grad-video"><div className="grad-section-heading"><p className="grad-eyebrow">El viaje en un minuto</p><h2>Imagina todo lo que<br /><em>vamos a vivir.</em></h2><p>Mar, diversión pirata y una celebración para cerrar juntos la secundaria.</p></div><video controls playsInline preload="none" poster={media + 'poster.jpg'} aria-label="Video promocional del viaje de graduación 2027"><source src={media + 'viaje-graduacion-2027.mp4'} type="video/mp4" />Tu navegador no permite reproducir este video. <a href={media + 'viaje-graduacion-2027.mp4'}>Descargar video</a></video><p className="grad-note">Imágenes conceptuales y fotografías de referencia. Las escenas ilustrativas no representan un montaje garantizado del evento.</p></section>
      <section id="hotel" className="grad-section grad-hotel"><div className="grad-section-heading"><p className="grad-eyebrow">Tu estancia frente al Pacífico</p><h2>Hilton Vallarta Riviera<br /><em>All-Inclusive Resort</em></h2><p>Habitaciones Ocean Front, playa, albercas y espacios para disfrutar en familia. Todo incluido durante la estancia.</p></div><div className="grad-gallery">{gallery.map(([file, label]) => <figure key={file}><a href={media + file} target="_blank" rel="noreferrer" aria-label={'Ver fotografía: ' + label}><img src={media + file} alt={label + ' en Hilton Vallarta Riviera'} width="960" height="540" loading="lazy" /></a><figcaption>{label}</figcaption></figure>)}</div><p className="grad-note">Fotografías oficiales de Hilton, utilizadas como referencia. La asignación de habitación y servicios se confirma según disponibilidad y contrato. <a href="https://www.hilton.com/en/hotels/pvrpahh-hilton-vallarta-riviera-all-inclusive-resort/" target="_blank" rel="noreferrer">Conocer el hotel ↗</a></p></section>
      <section id="paquete" className="grad-section"><div className="grad-section-heading"><p className="grad-eyebrow">Más que una estancia</p><h2>Un viaje para<br /><em>recordar juntos.</em></h2></div><div className="grad-inclusions">{included.map(([number,title,description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div><div className="grad-pirate"><img src={media + 'pirate-show.jpg'} alt="Show de piratas a bordo del barco del tour" loading="lazy" width="958" height="640" /><div><p className="grad-eyebrow">¡Todos a bordo!</p><h3>La aventura<br /><em>también va incluida.</em></h3><p>Una experiencia pirata para compartir risas, disfrutar el mar y crear recuerdos con tus compañeros.</p><div className="grad-pirate-thumbs"><img src={media + 'pirate-ship.jpg'} alt="Barco Pirata en el mar" loading="lazy" width="1024" height="1280" /><img src={media + 'pirate-food.jpg'} alt="Alimentos ofrecidos a bordo del Barco Pirata" loading="lazy" width="1200" height="800" /></div></div></div><div className="grad-celebrations">{[['sunset.jpg','Fotografías al atardecer','Los recuerdos merecen su mejor luz.'],['gala.jpg','Cena de gala de graduación','Una noche para celebrar esta etapa.']].map(([file,title,text]) => <figure key={file}><div className="grad-concept-image"><img src={media + file} alt={'Imagen conceptual de ' + title.toLowerCase()} width="960" height="540" loading="lazy" /><span>Imagen conceptual</span></div><figcaption><h3>{title}</h3><p>{text} <strong>Incluido en el paquete.</strong></p></figcaption></figure>)}</div></section>
      <section className="grad-family"><div className="grad-concept-image"><img src={media + 'family.jpg'} alt="Imagen conceptual de integración entre padres e hijos" loading="lazy" width="960" height="540" /><span>Imagen conceptual</span></div><div><p className="grad-eyebrow">Opcional · A elección de los padres</p><h2>Un momento para<br /><em>conectar de corazón.</em></h2><p>Un emotivo evento especial de integración entre padres e hijos, para reconocer lo vivido y acompañar juntos lo que viene.</p><p className="grad-note">Consulta con la organización las condiciones de esta actividad opcional.</p></div></section>
      <section id="reservacion" className="grad-section grad-reservation"><div><p className="grad-eyebrow">Prepara tu próxima aventura</p><h2>Tu graduación.<br /><em>Tu gran recuerdo.</em></h2><p>Cada estudiante viaja acompañado de una persona adulta responsable.</p><div className="grad-price"><span>Paquete por graduado</span><strong>$16,490 <small>MXN</small></strong><p>27–30 de mayo de 2027 · 4 días / 3 noches</p></div><div className="grad-payment"><strong>30% de anticipo · 8 mensualidades</strong><p>De acuerdo con contrato y calendario de pagos.</p></div><a href={contact} target="_blank" rel="noreferrer" className="grad-button">Solicitar información por WhatsApp ↗</a><p className="grad-note">Organiza Instituto Ascendant. Sujeto a disponibilidad y condiciones de contratación.</p></div><div className="grad-rate-card"><h3>Viaja en familia</h3><p>Tarifas del paquete en MXN.</p><table><caption className="sr-only">Tarifas para graduados y acompañantes</caption><tbody>{rates.map(([label,price]) => <tr key={label}><th scope="row">{label}</th><td>{price}</td></tr>)}</tbody></table><p className="grad-note">Las tarifas corresponden a la propuesta Hilton. Confirma ocupación, disponibilidad y condiciones con la organización antes de reservar.</p></div></section>
      <section className="grad-faq grad-section"><h2>Antes de reservar</h2><details><summary>¿Qué incluye el paquete?</summary><p>Hospedaje todo incluido durante la estancia, tour diurno en Barco Pirata, transporte hotel–embarcadero–hotel, fotografías al atardecer y cena de gala de graduación. El evento de integración entre padres e hijos es opcional, a elección de los padres.</p></details><details><summary>¿Pueden viajar padres y familiares?</summary><p>Sí. Consulta las tarifas de acompañantes y la ocupación de cada habitación. Cada estudiante debe viajar con una persona adulta responsable.</p></details><details><summary>¿Las imágenes corresponden al evento?</summary><p>Las habitaciones y áreas del hotel son fotografías oficiales de Hilton. Las fotografías del tour fueron proporcionadas para ilustrar la experiencia. Las escenas de atardecer, gala e integración son imágenes conceptuales.</p></details><details><summary>¿Cómo confirmo mi participación?</summary><p>Solicita información a Instituto Ascendant para conocer disponibilidad, contrato, anticipo, calendario de pagos y condiciones del evento opcional.</p></details></section>
    </main><Footer />
  </div>;
}
